#!/bin/bash

################################################################################
# compile_c.sh - Build standalone RV32I C programs to hex format
#
# Usage:
#   ./compile_c.sh <source.c> [more_sources.c ...] [options]
#
# Options:
#   --output <name>       Output base name (default: basename of first .c file)
#   --with-main           Inject a shim so user can write main() instead of
#                         init() / always(). main() is called once from init().
#   --no-runtime-utils    Exclude runtime/uart.c, runtime/seg7.c,
#                         runtime/button.c from the build.
#   --extra-flags <f>     Append extra flags to the compiler command.
#
# Program model (without --with-main):
#   The startup code in runtime/runtime.s calls init() once, then loops
#   forever calling always(). Both are declared __attribute__((weak)), so
#   you only need to define the ones you use.
#
# Program model (with --with-main):
#   Write a standard main() function; a generated shim calls it from init().
#
# Outputs:
#   <name>.elf   ELF executable
#   <name>.bin   Raw binary
#   <name>.hex   Verilog hex (one 32-bit word per line, for $readmemh)
#   <name>.dump  Disassembly listing
#
# Dependencies:
#   riscv32-unknown-elf-gcc (or riscv64 variant)
################################################################################

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RUNTIME_DIR="$SCRIPT_DIR/runtime"
LINKER_SCRIPT="$SCRIPT_DIR/linker.ld"

# --------------------------------------------------------------------------- #
# Parse arguments
# --------------------------------------------------------------------------- #
C_SOURCES=()
OUTPUT_NAME=""
WITH_MAIN=0
NO_RUNTIME_UTILS=0
EXTRA_FLAGS=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --output)
            OUTPUT_NAME="$2"; shift 2 ;;
        --with-main)
            WITH_MAIN=1; shift ;;
        --no-runtime-utils)
            NO_RUNTIME_UTILS=1; shift ;;
        --extra-flags)
            EXTRA_FLAGS="$2"; shift 2 ;;
        -*)
            echo "Unknown option: $1"; exit 1 ;;
        *)
            C_SOURCES+=("$1"); shift ;;
    esac
done

if [[ ${#C_SOURCES[@]} -eq 0 ]]; then
    echo "Usage: $0 <source.c> [more_sources.c ...] [options]"
    echo "       $0 --help   (show full help)"
    exit 1
fi

# Verify all source files exist
for f in "${C_SOURCES[@]}"; do
    if [[ ! -f "$f" ]]; then
        echo "Error: Source file '$f' not found"
        exit 1
    fi
done

# Default output name from the first source file
if [[ -z "$OUTPUT_NAME" ]]; then
    OUTPUT_NAME="$(basename "${C_SOURCES[0]}" .c)"
fi

# --------------------------------------------------------------------------- #
# Locate RISC-V toolchain
# --------------------------------------------------------------------------- #
if command -v riscv32-unknown-elf-gcc &>/dev/null; then
    PREFIX="riscv32-unknown-elf-"
elif command -v riscv64-unknown-elf-gcc &>/dev/null; then
    PREFIX="riscv64-unknown-elf-"
elif command -v riscv64-linux-gnu-gcc &>/dev/null; then
    PREFIX="riscv64-linux-gnu-"
else
    echo "Error: No RISC-V toolchain found!"
    echo "Install one of: riscv32-unknown-elf-gcc, riscv64-unknown-elf-gcc, riscv64-linux-gnu-gcc"
    exit 1
fi

echo "Using toolchain: ${PREFIX}gcc"

# --------------------------------------------------------------------------- #
# Validate required files
# --------------------------------------------------------------------------- #
if [[ ! -f "$LINKER_SCRIPT" ]]; then
    echo "Error: Linker script not found at '$LINKER_SCRIPT'"
    exit 1
fi
if [[ ! -f "$RUNTIME_DIR/runtime.s" ]]; then
    echo "Error: runtime/runtime.s not found in '$RUNTIME_DIR'"
    exit 1
fi

# --------------------------------------------------------------------------- #
# Build source list
# --------------------------------------------------------------------------- #
ALL_SOURCES=()

# 1) Startup assembly (must be first so _start lands at address 0)
ALL_SOURCES+=("$RUNTIME_DIR/runtime.s")

# 2) Runtime utility C files (uart, seg7, button)
if [[ $NO_RUNTIME_UTILS -eq 0 ]]; then
    for util in soft_div.c uart.c seg7.c button.c; do
        [[ -f "$RUNTIME_DIR/$util" ]] && ALL_SOURCES+=("$RUNTIME_DIR/$util")
    done
fi

# 3) --with-main shim: generate a tiny C translation unit in a temp dir
TMPDIR_SHIM=""
if [[ $WITH_MAIN -eq 1 ]]; then
    TMPDIR_SHIM="$(mktemp -d)"
    cat > "$TMPDIR_SHIM/main_shim.c" <<'EOF'
/* Auto-generated by compile_c.sh --with-main */
extern int main(void);

void init(void)
{
    main();
}
EOF
    ALL_SOURCES+=("$TMPDIR_SHIM/main_shim.c")
fi

# 4) User source files
ALL_SOURCES+=("${C_SOURCES[@]}")

# --------------------------------------------------------------------------- #
# Compiler / linker flags
# --------------------------------------------------------------------------- #
ARCH_FLAGS="-march=rv32i -mabi=ilp32"
OPT_FLAGS="-O2"
WARN_FLAGS="-Wall -Wextra"
BARE_FLAGS="-nostdlib -nostartfiles -ffreestanding -static -fno-pic"
INCLUDE_FLAGS="-I$RUNTIME_DIR"
GC_FLAGS="-ffunction-sections -fdata-sections -Wl,--gc-sections"

CFLAGS="$ARCH_FLAGS $OPT_FLAGS $WARN_FLAGS $BARE_FLAGS $INCLUDE_FLAGS $GC_FLAGS $EXTRA_FLAGS"

# --------------------------------------------------------------------------- #
# Build
# --------------------------------------------------------------------------- #
echo "========================================="
echo "Compiling C program"
echo "Sources:   ${C_SOURCES[*]}"
echo "Output:    $OUTPUT_NAME"
[[ $WITH_MAIN -eq 1 ]] && echo "Mode:      main() entry (shim injected)"
[[ $WITH_MAIN -eq 0 ]] && echo "Mode:      init() / always() entry"
[[ $NO_RUNTIME_UTILS -eq 1 ]] && echo "Utils:     excluded"
echo "========================================="

# Step 1: Compile & link to ELF
echo "Step 1: Compiling and linking..."
${PREFIX}gcc $CFLAGS \
    -T "$LINKER_SCRIPT" \
    -o "${OUTPUT_NAME}.elf" \
    "${ALL_SOURCES[@]}"

# Step 2: Raw binary
echo "Step 2: Creating binary..."
${PREFIX}objcopy -O binary "${OUTPUT_NAME}.elf" "${OUTPUT_NAME}.bin"

# Step 3: Verilog hex (one 32-bit word per line, little-endian)
echo "Step 3: Creating Verilog hex file..."
hexdump -v -e '1/4 "%08x\n"' "${OUTPUT_NAME}.bin" > "${OUTPUT_NAME}.hex"

# Step 4: Disassembly
echo "Step 4: Generating disassembly..."
${PREFIX}objdump -d -M numeric -S "${OUTPUT_NAME}.elf" > "${OUTPUT_NAME}.dump"

# Cleanup temp shim dir
[[ -n "$TMPDIR_SHIM" ]] && rm -rf "$TMPDIR_SHIM"

# --------------------------------------------------------------------------- #
# Summary
# --------------------------------------------------------------------------- #
echo ""
echo "========================================="
echo "Build successful!"
echo "========================================="
ls -lh "${OUTPUT_NAME}.elf" "${OUTPUT_NAME}.bin" "${OUTPUT_NAME}.hex" "${OUTPUT_NAME}.dump"

echo ""
echo "First 10 instructions:"
head -n 20 "${OUTPUT_NAME}.dump" | grep "^[[:space:]]*[0-9a-f]" || true

echo ""
echo "Hex file ready for simulation: ${OUTPUT_NAME}.hex"
